// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7fad9e1e4ea4a27bf3a43959586cb5684c6c584a/redux-immutable-state-invariant/index.d.ts
declare module 'redux-immutable-state-invariant' {
// Type definitions for react-router-redux v1.2.0
// Project: https://github.com/leoasis/redux-immutable-state-invariant
// Definitions by: Remo H. Jansen <https://github.com/remojansen>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="redux" />

import * as Redux from 'redux';

type isImmutableDefault = (value: any) => boolean;
type immutableStateInvariantMiddlewareInterface = (isImmutable?: isImmutableDefault) => Redux.Middleware;
let immutableStateInvariantMiddleware: immutableStateInvariantMiddlewareInterface;
export = immutableStateInvariantMiddleware;
}
